include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    # connerkasten@ thinks this is less readable to non-dart specialists
    use_null_aware_elements: false
