name: fullstory_dio
description: "Dio interception for Fullstory."
version: 0.0.1
homepage: "https://www.fullstory.com/platform/mobile-apps/"

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  fullstory_flutter: #^0.5.0+, we'll need to update this when we release
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  plugin_platform_interface: ^2.0.2

